name: howto_dockerfile
services:
    influxdb:
        image: influxdb:2.7.5-alpine
        environment:
            DOCKER_INFLUXDB_INIT_MODE: 'setup'
            DOCKER_INFLUXDB_INIT_USERNAME: 'howto_user'
            DOCKER_INFLUXDB_INIT_PASSWORD: 'howto_str0ng_passw0rd'
            DOCKER_INFLUXDB_INIT_ORG: 'howto_company'
            DOCKER_INFLUXDB_INIT_BUCKET: 'howto_company'
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 'C8TXsDAjcGfCKqZJY6fI+u268gUMdRWhj6MpbZexj38='
        volumes:
            - ./data/influxdb/data:/var/lib/influxdb2
            - ./data/influxdb/config:/etc/influxdb2

    bifrost-core:
        image: cr.siemens.com/bifrost/bifrost-zero:latest
        environment:
            BIFROST__server_host: '"::"'
            BIFROST__cdl_url: '"http://influxdb:8086"'
            BIFROST__cdl_org: '"howto_company"'
            BIFROST__cdl_user: '"howto_user"'
            BIFROST__cdl_token: '"C8TXsDAjcGfCKqZJY6fI+u268gUMdRWhj6MpbZexj38="'
            BIFROST__backup_autoImport: 'true'
        volumes:
            - ./data/story_volume/:/opt/bifrost/server/build/backup/
            - ./data/bsx_volume/:/opt/bifrost/server/build/imports/
            - ./config/:/opt/bifrost/server/build/server/config/user/
        ports:
            - '9091:9091'
        command: >
            sh -c "npm run start:server -- -- --config-user-module=howto-config.js"
