name: openswarm_scenarios
services:
    influxdb:
        image: $REGISTRY_INFLUXDB:$IMG_TAG_INFLUXDB
        environment:
            DOCKER_INFLUXDB_INIT_MODE: 'setup'
            DOCKER_INFLUXDB_INIT_USERNAME: 'openswarm_user'
            DOCKER_INFLUXDB_INIT_PASSWORD: 'openswarm_str0ng_passw0rd'
            DOCKER_INFLUXDB_INIT_ORG: 'openswarm'
            DOCKER_INFLUXDB_INIT_BUCKET: 'openswarm'
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 'C8TXsDAjcGfCKqZJY6fI+u268gUMdRWhj6MpbZexj38='
        volumes:
            - ../data/influxdb/data:/var/lib/influxdb2
            - ../data/influxdb/config:/etc/influxdb2

    bifrost-core:
        image: $REGISTRY_CORE:$IMG_TAG_CORE
        environment:
            BIFROST__server_host: '"::"'
            BIFROST__cdl_url: '"http://influxdb:8086"'
            BIFROST__cdl_org: '"openswarm"'
            BIFROST__cdl_user: '"openswarm_user"'
            BIFROST__cdl_token: '"C8TXsDAjcGfCKqZJY6fI+u268gUMdRWhj6MpbZexj38="'
            # BIFROST__backup_autoImport: 'true'
        volumes:
            - ../data/story_volume/:/opt/bifrost/server/build/backup/
            - ../images/:/opt/bifrost/server/build/public/custom/
            #  - ../data/bsx_volume/:/opt/bifrost/server/build/imports/
            - ../fragments/core/:/opt/bifrost/server/fragment/
            - ../configs/core/:/opt/bifrost/server/build/server/config/user/
        ports:
            - '9091:9091'
        command: |
            sh -c "
                npm run build:server && 
                npm run start:server -- -- --config-user-module=openswarm-scenarios-core-config.js
            "
    
    fenrir:
        image: cr.siemens.com/bifrost/bifrost-fenrir:zero-v1.3.0
        environment:
            MODULE_URL: "http://fenrir:7001"
            BIFROST_URL: "http://bifrost-core:9091"
            SAMPLING_RATE: 900
        volumes:
            - ../configs/fenrir/:/app/config/
            - ../fragments/fenrir/:/app/fragments/
        depends_on:
            - bifrost-core
